name: 'Code sign a file with pfx certificate'
description: 'Sign a file with a pfx certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the files to sign.'
    required: true
  recursive:
    description: 'Recursively search for supported files.'
    required: false
  password:
    description: 'The password'
    required: false
  certificatesha1:
    description: 'The sha1 or fingerprint of the certification'
    required: false
  certificatename:
    description: 'The Name of the certificate'
    required: false
  timestampUrl:
    description: 'URL of the timestamp server'
    required: false
  debug:
    description: 'Enable debug option'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
